lab3/blog/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('blog/', views.index, name="home"),
    path('login/', views.LoginUserView.as_view(), name="login"),
    path('register/', views.RegisterUserView.as_view(), name="register"),
    path('logout/', views.logout_view, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('create/', views.CreatePost, name="create"),
    path('blog/<int:pk>/comment/', views.BlogCommentCreate.as_view(), name='blog_comment'),
    path('blogger/<int:pk>', views.BlogListbyAuthorView.as_view(), name='blog_author'),
    path('blog/<int:pk>', views.BlogDetailView.as_view(), name='blog-detail'),
]

lab3/lab3/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

lab3/blog/models.py
from django.db import models
from datetime import date
from django.urls import reverse
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=400, help_text="Enter your bio details here.")
    image = models.ImageField(default='default.png  ', upload_to='profile_pics')

    class Meta:
        ordering = ["user", "bio", "image"]

    def get_absolute_url(self):
        return reverse('blogs-by-author', args=[str(self.id)])

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)




class Blog(models.Model):
    name = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField(max_length=2000, help_text="Enter you blog text here.")
    post_date = models.DateField(default=date.today)

    class Meta:
        ordering = ["-post_date"]

    def get_absolute_url(self):
        return reverse('blog-detail', args=[str(self.id)])

    def __str__(self):
        return self.name





class BlogComment(models.Model):
    description = models.TextField(max_length=1000, help_text="Enter comment about blog here.")
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    post_date = models.DateTimeField(auto_now_add=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    class Meta:
        ordering = ["post_date"]

    def __str__(self):
        len_title = 75
        if len(self.description) > len_title:
            titlestring = self.description[:len_title] + '...'
        else:
            titlestring = self.description
        return titlestring

lab3/blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, Blog


class RegisterUserForm(UserCreationForm):
    password1 = forms.CharField(help_text="", label="Пароль", widget=forms.PasswordInput)
    password2 = forms.CharField(help_text="", label="Подтвердите пароль", widget=forms.PasswordInput)
    username = forms.CharField(help_text="", label="Логин")
    email = forms.CharField(help_text="", label="Электронная почта")

    class Meta:
        model = User
        fields = ["username", "password1", "password2", "email"]


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

class CreateBlogPost(forms.ModelForm):
    name = forms.CharField(help_text="", label="Имя")
    description = forms.CharField(help_text="", label="Описание")

    class Meta:
        model = Blog
        fields = ['name', 'description']


lab3/blog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.template.context_processors import request
from django.views import generic

from . import forms
from django.contrib.auth.views import LoginView
from django.views.generic import CreateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth import logout
from .forms import UserUpdateForm, ProfileUpdateForm
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from .models import Profile, Blog, BlogComment
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse

def index(request):
    blog = Blog.objects.all()
    return render(request, 'index.html', {"blog":blog})

class BlogDetailView(generic.DetailView):
    template_name = 'blog.html'
    model = Blog


class BlogListbyAuthorView(generic.ListView):
    model = Blog
    paginate_by = 5
    template_name ='author.html'

    def get_queryset(self):
        id = self.kwargs['pk']
        target_author=get_object_or_404(User, pk = id)
        return Blog.objects.filter(author=target_author)

    def get_context_data(self, **kwargs):
        context = super(BlogListbyAuthorView, self).get_context_data(**kwargs)
        context['blogger'] = get_object_or_404(User, pk = self.kwargs['pk'])
        return context



class BlogCommentCreate(LoginRequiredMixin, CreateView):
    model = BlogComment
    fields = ['description',]
    template_name = 'comment.html'

    def get_context_data(self, **kwargs):
        context = super(BlogCommentCreate, self).get_context_data(**kwargs)
        context['blog'] = get_object_or_404(Blog, pk = self.kwargs['pk'])
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.blog=get_object_or_404(Blog, pk = self.kwargs['pk'])
        return super(BlogCommentCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse('blog-detail', kwargs={'pk': self.kwargs['pk'],})






class RegisterUserView(CreateView):
    model = User
    form_class = forms.RegisterUserForm
    template_name = "register.html"
    success_url = reverse_lazy("login")

    def form_valid(self, form):
        # Save the user object without committing to the database
        user = form.save(commit=False)
        # Set the user's password
        user.set_password(form.cleaned_data.get('password'))
        user.save()

        # Create a profile for the user
        Profile.objects.create(user=user)

        return super().form_valid(form)

class LoginUserView(LoginView):
    template_name = "login.html"

def logout_view(request):
    logout(request)
    return redirect("login")

# class CreatePost(CreateView):
#     model = Blog
#     form_class = forms.CreateBlogPost
#     template_name = "create_blog.html"
#     success_url = reverse_lazy("home")
#
#     def form_valid(self, form):
#         post = form.save()
#         print(post)
#         Blog.objects.create(name=post, author=request.user.Profile)
#         return super().form_valid(form)

def CreatePost(request):
    if request.method == 'POST':
        form = forms.CreateBlogPost(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('home')  # Перенаправляем на страницу со списком постов
    else:
        form = forms.CreateBlogPost()
    return render(request, 'create_blog.html', {'form': form})




@login_required()
def profile(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, f'Ваш аккаунт был обновлен!')
            return redirect('profile')

    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'user_form': user_form,
        'profile_form': profile_form
    }

    return render(request, 'profile.html', context)

lab3/blog/templates/author.html
{% extends 'layout.html' %}

{% block content %}
    <h1>Автор: {{blogger}}</h1>
    <h3>Bio</h3>
    <p>{{blogger.bio}}</p>
    {% if blog_list %}
    <h3>Blogs list</h3>
    <ul>
      {% for blog in blog_list %}
      <li>
        <a href="{{ blog.get_absolute_url }}">{{ blog.name }}</a> ({{blog.post_date}})</a>
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>This blogger hasn't posted anything yet.</p>
    {% endif %}

{% endblock %}

lab3/blog/templates/blog.html
{% extends 'layout.html' %}

{% block content %}

<h1>{{ blog.name }}</h1>
<p><strong>Дата</strong> {{ blog.post_date }}</p>
<p><strong>Автор:</strong> <a href="{% url 'blog_author' blog.author.pk %}">{{ blog.author }}</a></p>
<p><strong>Описание:</strong></p>
<p style="white-space:pre-wrap;">{{ blog.description }}</p>

<div style="margin-left:20px;margin-top:20px">
<h4>Комментарии</h4>

{% for comment in blog.blogcomment_set.all %}
<hr>
<p>{{comment.author}} ({{comment.post_date}}) - {{comment.description}}</p>
{% endfor %}
<hr>
{% if user.is_authenticated %}
  <a href="{% url 'blog_comment' blog.id %}">Добавить комментарий</a></p>
{% else %}
  <p><a href="{% url 'login'%}?next={{request.path}}">Login</a> to add a new comment</p>
{% endif %}


</div>
{% endblock %}

lab3/blog/templates/comment.html
{% extends 'layout.html' %}

{% block content %}
  <p>Post your comment for: <a href="{% url 'blog-detail' blog.pk %}">{{blog.name}}</a></p>

  <form action="" method="post">
      {% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>
      <input type="submit" value="Submit" />

  </form>
{% endblock %}

lab3/blog/templates/create_blog.html
{% extends 'layout.html' %}


{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Подтвердить</button>
</form>
{% endblock %}

lab3/blog/templates/index.html
{% extends 'layout.html' %}

{% block content %}
    {% for b in blog %}
    <div class="posts">
        <a href="{{ b.get_absolute_url }}">{{ b.name }}</a>
        {{ b.post_date }}
        <a href="{% url 'blog_author' b.author.pk %}">{{ b.author }}</a>
    </div>
    {% endfor %}
{% endblock %}

lab3/blog/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body>
        {% if user.is_authenticated %}
            <div class="links">
                <a href="{% url 'home' %}">Главная</a>
                <a href="{% url 'create' %}">Создать</a>
                <a href="{% url 'profile' %}">Профиль</a>
                <a href="{% url 'logout' %}">Выйти</a>
            </div>
        {% else %}
                    <div class="links">
                <a href="{% url 'login' %}">Войти</a>
                <a href="{% url 'register' %}">Регистрация</a>
                    </div>
        {% endif %}

        {% block content %}
    {% endblock %}
</body>
</html>

lab3/blog/templates/login.html
{% extends 'layout.html' %}


{% block content %}
    <div class="login-page">
      <div class="form">
        <form class="login-form" method="POST">
          {% csrf_token %}
          {{ form.as_p }}
            <button type="submit">ВОЙТИ</button>
          <p class="message">Нет аккаунта? <a href="{% url 'register' %}">Создать</a></p>
        </form>
      </div>
    </div>
{% endblock %}

lab3/blog/templates/profile.html
{% extends 'layout.html' %}

{% block content %}
        <div class="container d-flex justify-content-center align-items-center">
             <div class="card">
                 <div class="text-center">
                <h2 class="mb-0">{{ user.username }}</h2>
              </div>
              <div class="user text-center">
                <div class="profile">
                    <form class="profile_form" method="POST" enctype="multipart/form-data">
                        {% for field1 in profile_form %}
                            <img src="{{ field1.value.url }}" alt="">
                        {{ field1 }}
                        {% endfor %}
                        {% csrf_token %}
                        {% for field in user_form %}
                            {{field.label}}
                            {{field}}
                        {% endfor %}

                        <button type="submit">Обновить</button>
                    </form>
                </div>
              </div>
             </div>
           </div>
{% endblock %}

lab3/blog/templates/register.html
{% extends 'layout.html' %}


{% block content %}
    <div class="login-page">
      <div class="form">
        <form class="register-form" method="post">
        {% csrf_token %}
          {{ form.as_p }}
            <button type="submit">Создать</button>
        </form>
      </div>
    </div>
{% endblock %}